baseURL = "http://guowei7.gitee.io/guowei"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "郭微blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "三体"
author = "guowei"
description = "给岁月以文明，而不是给文明以岁月。"  
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
#[[params.socialIcons]]
#icon = "fa-linkedin"
#title = "Linkedin"
#url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/guowei7"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:770857344@qq.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "Home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Post"
  weight = 200
  identifier = "Post"
  url = "/post/"

  #[[menu.main]]
  #name = "关于"
  #weight = 300
  #identifier = "关于"
  #url = "/about/"
